/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GiftKitsRouteImport } from './routes/gift-kits'
import { Route as CustomizationRouteImport } from './routes/customization'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const GiftKitsRoute = GiftKitsRouteImport.update({
  id: '/gift-kits',
  path: '/gift-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizationRoute = CustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/gift-kits': typeof GiftKitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/gift-kits': typeof GiftKitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/customization': typeof CustomizationRoute
  '/gift-kits': typeof GiftKitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/catalog'
    | '/contact'
    | '/customization'
    | '/gift-kits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/catalog'
    | '/contact'
    | '/customization'
    | '/gift-kits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/catalog'
    | '/contact'
    | '/customization'
    | '/gift-kits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  CustomizationRoute: typeof CustomizationRoute
  GiftKitsRoute: typeof GiftKitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gift-kits': {
      id: '/gift-kits'
      path: '/gift-kits'
      fullPath: '/gift-kits'
      preLoaderRoute: typeof GiftKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customization': {
      id: '/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof CustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  CustomizationRoute: CustomizationRoute,
  GiftKitsRoute: GiftKitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
